name: Feature request
description: Propose an improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true
